# frozen_string_literal: true

module Authsnitch
  # Formats detection results into human-readable summaries
  class Summarizer
    # Generate a comprehensive summary from detection results
    # @param detection_result [Detector::DetectionResult] Detection result from Claude
    # @param score_result [Hash] Score result from RiskScorer
    # @param pr_info [Hash] PR metadata (title, number, author, repo, url)
    # @param keywords_detected [Array<String>] Keywords found in the diff
    # @return [Hash] Formatted summary with sections
    def summarize(detection_result:, score_result:, pr_info: {}, keywords_detected: [])
      {
        title: build_title(score_result),
        risk_display: build_risk_display(score_result),
        pr_section: build_pr_section(pr_info),
        summary: detection_result.summary,
        findings: format_findings(detection_result.findings),
        files_affected: extract_affected_files(detection_result.findings),
        keywords: keywords_detected,
        recommendations: extract_recommendations(detection_result.findings),
        score_breakdown: score_result[:breakdown]
      }
    end

    # Generate markdown-formatted summary for PR comments
    # @param summary [Hash] Summary from #summarize
    # @return [String] Markdown text
    def to_markdown(summary)
      lines = []

      # Header with risk badge
      lines << "## #{summary[:title]}"
      lines << ""
      lines << summary[:risk_display][:text]
      lines << ""

      # PR Info
      if summary[:pr_section][:title]
        lines << "**PR:** #{summary[:pr_section][:title]}"
        lines << "**Author:** #{summary[:pr_section][:author]}" if summary[:pr_section][:author]
        lines << ""
      end

      # Summary
      lines << "### Summary"
      lines << summary[:summary]
      lines << ""

      # Findings
      if summary[:findings].any?
        lines << "### Findings"
        summary[:findings].each do |finding|
          lines << ""
          lines << "#### #{finding[:type_display]}"
          lines << "**File:** `#{finding[:file]}`"
          lines << "**Risk:** #{finding[:risk_badge]}"
          lines << ""
          lines << finding[:description]
          lines << ""
          lines << "> **Why this matters:** #{finding[:security_relevance]}"
          lines << ""
          if finding[:recommendation]
            lines << "**Recommendation:** #{finding[:recommendation]}"
            lines << ""
          end
        end
      end

      # Files Affected
      if summary[:files_affected].any?
        lines << "### Files Affected"
        summary[:files_affected].each do |file|
          lines << "- `#{file}`"
        end
        lines << ""
      end

      # Keywords Detected
      if summary[:keywords].any?
        lines << "### Keywords Detected"
        lines << summary[:keywords].map { |kw| "`#{kw}`" }.join(', ')
        lines << ""
      end

      # Score Breakdown
      if summary[:score_breakdown][:modifiers].any?
        lines << "### Score Breakdown"
        lines << "- Base score: #{summary[:score_breakdown][:base_score]} (#{summary[:score_breakdown][:highest_risk]} risk)"
        summary[:score_breakdown][:modifiers].each do |mod|
          lines << "- +#{mod[:points]}: #{mod[:reason]}"
        end
        lines << ""
      end

      lines << "---"
      lines << "*Generated by AuthSnitch Security Review*"

      lines.join("\n")
    end

    # Generate plain text summary
    # @param summary [Hash] Summary from #summarize
    # @return [String] Plain text
    def to_text(summary)
      lines = []

      lines << summary[:title]
      lines << "=" * summary[:title].length
      lines << ""
      lines << "Risk Score: #{summary[:risk_display][:score]} (#{summary[:risk_display][:label]})"
      lines << ""
      lines << "Summary: #{summary[:summary]}"
      lines << ""

      if summary[:findings].any?
        lines << "Findings:"
        summary[:findings].each_with_index do |finding, i|
          lines << "  #{i + 1}. #{finding[:type_display]} [#{finding[:risk_level].upcase}]"
          lines << "     File: #{finding[:file]}"
          lines << "     #{finding[:description]}"
          lines << ""
        end
      end

      if summary[:files_affected].any?
        lines << "Files Affected: #{summary[:files_affected].join(', ')}"
        lines << ""
      end

      if summary[:keywords].any?
        lines << "Keywords: #{summary[:keywords].join(', ')}"
      end

      lines.join("\n")
    end

    private

    def build_title(score_result)
      case score_result[:label]
      when 'CRITICAL'
        'AuthSnitch Security Alert - CRITICAL'
      when 'HIGH'
        'AuthSnitch Security Alert - HIGH RISK'
      when 'MEDIUM'
        'AuthSnitch Security Notice - MEDIUM RISK'
      else
        'AuthSnitch Security Review'
      end
    end

    def build_risk_display(score_result)
      score = score_result[:score]
      label = score_result[:label]

      # Build visual progress bar
      filled = (score / 10.0).round
      empty = 10 - filled
      bar = "[#{'*' * filled}#{'-' * empty}]"

      {
        score: score,
        label: label,
        color: score_result[:color],
        bar: bar,
        text: "**Risk Score: #{score} (#{label})** #{bar}"
      }
    end

    def build_pr_section(pr_info)
      {
        title: pr_info[:title] ? "##{pr_info[:number]} \"#{pr_info[:title]}\"" : nil,
        number: pr_info[:number],
        author: pr_info[:author] ? "@#{pr_info[:author]}" : nil,
        repo: pr_info[:repo],
        url: pr_info[:url]
      }
    end

    def format_findings(findings)
      findings.map do |finding|
        {
          type: finding.type,
          type_display: humanize_type(finding.type),
          file: finding.file,
          code_section: finding.code_section,
          description: finding.description,
          security_relevance: finding.security_relevance,
          risk_level: finding.risk_level,
          risk_badge: risk_badge(finding.risk_level),
          recommendation: finding.recommendation
        }
      end
    end

    def humanize_type(type)
      return 'Unknown Change' unless type

      type.to_s
          .gsub('_', ' ')
          .split
          .map(&:capitalize)
          .join(' ')
    end

    def risk_badge(level)
      case level.to_s.downcase
      when 'critical'
        '`CRITICAL`'
      when 'high'
        '`HIGH`'
      when 'medium'
        '`MEDIUM`'
      when 'low'
        '`LOW`'
      else
        '`NONE`'
      end
    end

    def extract_affected_files(findings)
      findings.map(&:file).compact.uniq
    end

    def extract_recommendations(findings)
      findings
        .map(&:recommendation)
        .compact
        .reject(&:empty?)
        .uniq
    end
  end
end
