# frozen_string_literal: true

require 'spec_helper'

RSpec.describe Lilbro::Summarizer do
  subject(:summarizer) { described_class.new }

  let(:detection_result) do
    Lilbro::Detector::DetectionResult.new(
      findings: [
        Lilbro::Detector::Finding.new(
          type: 'oauth_integration',
          file: 'lib/auth/oauth_handler.rb',
          code_section: 'def authenticate(token)',
          description: 'New OAuth token validation logic',
          security_relevance: 'Token handling affects authentication security',
          risk_level: 'high',
          recommendation: 'Review token validation and expiry logic'
        )
      ],
      summary: 'OAuth integration changes detected with new token handling.',
      auth_changes_detected: true,
      highest_risk: 'high',
      raw_response: nil
    )
  end

  let(:score_result) do
    {
      score: 72,
      label: 'HIGH',
      color: '#ff9800',
      breakdown: {
        base_score: 65,
        highest_risk: 'high',
        modifiers: [
          { name: 'identity_provider_change', points: 7, reason: 'OAuth integration' }
        ],
        modifier_total: 7
      }
    }
  end

  let(:pr_info) do
    {
      title: 'Add OAuth login flow',
      number: 123,
      author: 'developer',
      repo: 'org/repo',
      url: 'https://github.com/org/repo/pull/123'
    }
  end

  describe '#summarize' do
    it 'creates a complete summary hash' do
      result = summarizer.summarize(
        detection_result: detection_result,
        score_result: score_result,
        pr_info: pr_info,
        keywords_detected: %w[oauth token]
      )

      expect(result).to include(
        :title,
        :risk_display,
        :pr_section,
        :summary,
        :findings,
        :files_affected,
        :keywords,
        :recommendations
      )
    end

    it 'formats risk display correctly' do
      result = summarizer.summarize(
        detection_result: detection_result,
        score_result: score_result,
        pr_info: pr_info,
        keywords_detected: []
      )

      expect(result[:risk_display][:score]).to eq(72)
      expect(result[:risk_display][:label]).to eq('HIGH')
      expect(result[:risk_display][:bar]).to match(/\[.*\]/)
    end

    it 'extracts affected files from findings' do
      result = summarizer.summarize(
        detection_result: detection_result,
        score_result: score_result,
        pr_info: pr_info,
        keywords_detected: []
      )

      expect(result[:files_affected]).to include('lib/auth/oauth_handler.rb')
    end

    it 'formats findings with display information' do
      result = summarizer.summarize(
        detection_result: detection_result,
        score_result: score_result,
        pr_info: pr_info,
        keywords_detected: []
      )

      finding = result[:findings].first
      expect(finding[:type_display]).to eq('Oauth Integration')
      expect(finding[:risk_badge]).to eq('`HIGH`')
    end
  end

  describe '#to_markdown' do
    it 'generates valid markdown' do
      summary = summarizer.summarize(
        detection_result: detection_result,
        score_result: score_result,
        pr_info: pr_info,
        keywords_detected: %w[oauth token session]
      )

      markdown = summarizer.to_markdown(summary)

      expect(markdown).to include('## LilBro Security Alert')
      expect(markdown).to include('**Risk Score: 72 (HIGH)**')
      expect(markdown).to include('### Summary')
      expect(markdown).to include('### Findings')
      expect(markdown).to include('`lib/auth/oauth_handler.rb`')
      expect(markdown).to include('`oauth`')
      expect(markdown).to include('*Generated by LilBro Security Review*')
    end

    it 'includes recommendations section' do
      summary = summarizer.summarize(
        detection_result: detection_result,
        score_result: score_result,
        pr_info: pr_info,
        keywords_detected: []
      )

      markdown = summarizer.to_markdown(summary)

      expect(markdown).to include('**Recommendation:**')
    end
  end

  describe '#to_text' do
    it 'generates plain text summary' do
      summary = summarizer.summarize(
        detection_result: detection_result,
        score_result: score_result,
        pr_info: pr_info,
        keywords_detected: %w[oauth]
      )

      text = summarizer.to_text(summary)

      expect(text).to include('Risk Score: 72 (HIGH)')
      expect(text).to include('Oauth Integration [HIGH]')
      expect(text).to include('lib/auth/oauth_handler.rb')
    end
  end
end
